sudo: false
dist: trusty

jobs:
  include:
    - stage: Build Docker Image
      before_script:
      - docker login -u=jakobchr -p="$DOCKER_PASSWORD"
      script:
      - docker pull jakobchr/fogproject:latest
      - docker build --cache-from jakobchr/fogproject:latest -t jakobchr/fogproject:latest .
      - docker images
      after_success:
      - docker push jakobchr/fogproject