sudo: true
dist: trusty

jobs:
  include:
    - stage: Build Docker Image
      script:
      - docker login -u=jakobchr -p="$DOCKER_PASSWORD"
      - docker build -t --cache-from jakobchr/fogproject:latest jakobchr/fogproject:latest .
      - docker images
      - docker push jakobchr/fogproject